[Application]
locale=en_US

[Export]
lastUsedExporter=Pandoc
smartTypographyEnabled=true

[FileHistory]
1\cursorPosition=1716
1\filePath=/home/kroybal/Documents/notes/assets/declaration_of_kirk_roybal_20240209.md
2\cursorPosition=459
2\filePath=/home/kroybal/Documents/untitled-1.md
3\cursorPosition=781
3\filePath=/home/kirk/Documents/pandoc_notes/journal_2022_08_29.md
size=2

[FindReplace]
highlightMatches=false
matchCase=false
regularExpression=false
wholeWord=false

[Preview]
codeFont="Noto Sans Mono,12,-1,5,50,0,0,0,0,0"
htmlPreviewOpen=true
lastUsedExporter=cmark-gfm
textFont="Noto Serif,12,-1,5,50,0,0,0,0,0"

[Save]
autoSave=true
backupFile=true

[Session]
favoriteStatistic=0
rememberFileHistory=true
restoreSession=true

[Spelling]
liveSpellCheck=true
locale=en_US

[Style]
blockquoteStyle=false
darkModeEnabled=true
displayTimeInFullScreen=true
editorFont="Noto Sans Mono,12,-1,5,50,0,0,0,0,0"
editorWidth=1
focusMode=1
hideMenuBarInFullScreenEnabled=true
interfaceStyle=0
largeHeadings=true
theme=Classic
underlineInsteadOfItalics=false

[Tabs]
insertSpacesForTabs=false
tabWidth=4

[Typing]
autoMatchEnabled=true
autoMatchFilter=\"'([{*_`<
bulletPointCyclingEnabled=true

[Window]
mainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x4\x38\0\0\x1\x35\0\0\bo\0\0\x6\xe9\0\0\x4\x38\0\0\x1R\0\0\bo\0\0\x6\xe9\0\0\0\x2\0\0\0\0\x4\x38\0\0\x4\x38\0\0\x1R\0\0\bo\0\0\x6\xe9)
mainWindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x4\x38\0\0\x5[\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)
sidebarOpen=true
